apple_shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('ecomapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomapp/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView
from . views import *


urlpatterns = [
    url(r'^category/(?P<category_slug>[-\w]+)/$', category_view, name='category_detail'),
    url(r'^product/(?P<product_slug>[-\w]+)/$', product_view, name='product_detail'),
    url(r'^add_to_cart/$', add_to_cart_view, name='add_to_cart'),
    url(r'^remove_from_cart/$', remove_from_cart_view, name='remove_from_cart'),
    url(r'^change_item_qty/$', change_item_qty, name='change_item_qty'),
    url(r'^cart/$', cart_view, name='cart'),
    url(r'^checkout/$', checkout_view, name='checkout'),
    url(r'^order/$', order_create_view, name='create_order'),
    url(r'^make_order/$', make_order_view, name='make_order'),
    url(r'^thank_you/$', TemplateView.as_view(template_name='thank_you.html'), name='thank_you'), 
    url(r'^account/$', account_view, name='account'),
    url(r'^registration/$', registration_view, name='registration'),
    url(r'^login/$', login_view, name='login'),
    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('base')), name='logout'),    
    url(r'^$', base_view, name='base'),
]

ecomapp/models.py
from decimal import Decimal
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.core.urlresolvers import reverse




class Category(models.Model):

    name = models.CharField(max_length=100)
    slug = models.SlugField(blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'category_slug': self.slug})

def pre_save_category_slug(sender, instance, *args, **kwargs):
    if not instance.slug:
        slug = slugify(instance.name)
        instance.slug = slug

pre_save.connect(pre_save_category_slug, sender=Category)


class Brand(models.Model):

    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


def image_folder(instance, filename):
    filename = instance.slug + '.' + filename.split('.')[1]
    return "{0}/{1}".format(instance.slug, filename)


class ProductManager(models.Manager):

    def all(self, *args, **kwargs):
        return super(ProductManager, self).get_queryset().filter(available=True)

class Product(models.Model):

    category = models.ForeignKey(Category)
    brand = models.ForeignKey(Brand)
    title = models.CharField(max_length=120)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField(upload_to=image_folder)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    available = models.BooleanField(default=True)
    objects = ProductManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'product_slug': self.slug})


class CartItem(models.Model):

    product = models.ForeignKey(Product)
    qty = models.PositiveIntegerField(default=1)
    item_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)

    def __str__(self):
        return "Cart item for product {0}".format(self.product.title)


class Cart(models.Model):

    items = models.ManyToManyField(CartItem, blank=True)
    cart_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)

    def __str__(self):
        return str(self.id)

    def add_to_cart(self, product_slug):
        cart = self
        product = Product.objects.get(slug=product_slug)
        new_item, _ = CartItem.objects.get_or_create(product=product, item_total=product.price)
        if new_item not in cart.items.all():
            cart.items.add(new_item)
            cart.save()
    
    def remove_from_cart(self, product_slug):
        cart = self
        product = Product.objects.get(slug=product_slug)
        for cart_item in cart.items.all():
            if cart_item.product == product:
                cart.items.remove(cart_item)
                cart.save()
    
    def change_qty(self, qty, item_id):
        cart = self
        cart_item = CartItem.objects.get(id=int(item_id))
        cart_item.qty = int(qty)
        cart_item.item_total = int(qty) * Decimal(cart_item.product.price)
        cart_item.save()
        new_cart_total = 0.00
        for item in cart.items.all():
            new_cart_total += float(item.item_total)
        cart.cart_total = new_cart_total
        cart.save()

ORDER_STATUS_CHOICES = (
    ('Accepted for processing', 'Accepted for processing'),
    ('Is carried out', 'Is carried out'),
    ('Paid', 'Paid')
)


class Order(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    items = models.ForeignKey(Cart)
    total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=255)
    buying_type = models.CharField(max_length=40, choices=(('With no deliveries','With no deliveries'),('Delivery', 'Delivery')), default='With no deliveries')
    date = models.DateTimeField(auto_now_add=True)
    comments = models.TextField()
    status = models.CharField(max_length=100, choices=ORDER_STATUS_CHOICES, default=ORDER_STATUS_CHOICES[0][0])

    def __str__(self):
        return "Order №:{0}".format(str(self.id))

    

ecomapp/views.py
from decimal import Decimal
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.core.urlresolvers import reverse
from django.contrib.auth import login, authenticate 
from ecomapp.forms import OrderForm, RegistrationForm, LoginForm
from . models import Category, Product, CartItem, Cart, Order


def base_view(request):
    try: 
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id )
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id 
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    categories = Category.objects.all()
    products = Product.objects.all()
    context = {
        'categories': categories,
        'products': products,
        'cart': cart   
    }

    return render(request, 'base.html', context)


def product_view(request, product_slug):
    try: 
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id )
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id 
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product = Product.objects.get(slug=product_slug)
    categories = Category.objects.all()
    context = {
        'product': product,
        'categories': categories,
        'cart': cart
    }
    return render(request, 'product.html', context)


def category_view(request, category_slug):
    category = Category.objects.get(slug=category_slug)
    categories = Category.objects.all()
    products_of_category = Product.objects.filter(category=category)
    context = {
        'category': category,
        'products_of_category': products_of_category,
        'categories': categories
    }
    return render(request, 'category.html', context)


def cart_view(request):
    try: 
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id )
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id 
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    categories = Category.objects.all()
    context = {
        'cart': cart,
        'categories': categories
    }
    return render(request, 'cart.html', context)


def add_to_cart_view(request):
    try: 
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id )
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id        
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product_slug = request.GET.get('product_slug')
    product = Product.objects.get(slug=product_slug)
    cart.add_to_cart(product.slug)
    new_cart_total = 0.00
    for item in cart.items.all():
        new_cart_total += float(item.item_total)
    cart.cart_total = new_cart_total
    cart.save()
    return JsonResponse({'cart_total': cart.items.count(), 'cart_total_price': cart.cart_total})


def remove_from_cart_view(request,):
    try: 
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id )
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id 
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product_slug = request.GET.get('product_slug')
    product = Product.objects.get(slug=product_slug)
    cart.remove_from_cart(product.slug)
    new_cart_total = 0.00
    for item in cart.items.all():
        new_cart_total += float(item.item_total)
    cart.cart_total = new_cart_total
    cart.save()
    return JsonResponse({'cart_total': cart.items.count(), 'cart_total_price': cart.cart_total})


def change_item_qty(request):
    try: 
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id )
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id 
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    qty = request.GET.get('qty')
    item_id = request.GET.get('item_id')
    print(qty, item_id)
    cart_item = CartItem.objects.get(id=int(item_id))
    cart.change_qty(qty, item_id)
    cart_item.item_total = int(qty) * Decimal(cart_item.product.price)
    cart_item.save()
    return JsonResponse(
        {'cart_total': cart.items.count(),
         'item_total': cart_item.item_total,
         'cart_total_price': cart.cart_total})


def checkout_view(request):
    try: 
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id )
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id 
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    categories = Category.objects.all()
    context = {
        'cart': cart,
        'categories': categories
    }
    return render(request, 'checkout.html', context)


def order_create_view(request):
    try: 
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id )
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id 
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    form = OrderForm(request.POST or None)
    categories = Category.objects.all()
    context = {
        'form': form,
        'cart': cart,
        'categories': categories
    }
    return render(request, 'order.html', context)


def make_order_view(request):
    try: 
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id )
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id 
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    form = OrderForm(request.POST or None)
    categories = Category.objects.all()
    if form.is_valid():
        name = form.cleaned_data['name']
        last_name = form.cleaned_data['last_name']
        phone = form.cleaned_data['phone']
        buying_type = form.cleaned_data['buying_type']
        address = form.cleaned_data['address']
        comments = form.cleaned_data['comments']
        new_order = Order.objects.create(
            user=request.user,
            items=cart,
            total=cart.cart_total,
            first_name=name,
            last_name=last_name,
            phone=phone,
            address=address,
            buying_type=buying_type,
            comments=comments
        )
        del request.session['cart_id']
        del request.session['total']
        return HttpResponseRedirect(reverse('thank_you'))
    return render(request, 'order.html',{'categories': categories})


def account_view(request):
    order = Order.objects.filter(user=request.user).order_by('-id')
    categories = Category.objects.all()
    context = {
        'order': order,
        'categories': categories
    }
    return render(request, 'account.html', context)


def registration_view(request):
    form = RegistrationForm(request.POST or None)
    categories = Category.objects.all()
    if form.is_valid():
        new_user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        email = form.cleaned_data['email']
        first_name = form.cleaned_data['first_name']
        last_name = form.cleaned_data['last_name']
        new_user.username = username
        new_user.set_password(password)
        new_user.first_name = first_name
        new_user.last_name = last_name
        new_user.email = email
        new_user.save()
        login_user = authenticate(username=username, password=password)
        if login_user:
            login(request, login_user)
            return HttpResponseRedirect(reverse('base'))
    context = {
        'form': form,
        'categories': categories
    }
    return render(request, 'registration.html', context)


def login_view(request):
    form = LoginForm(request.POST or None)
    categories = Category.objects.all()
    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        login_user = authenticate(username=username, password=password)
        if login_user:
            login(request, login_user)
            return HttpResponseRedirect(reverse('base'))
    context = {
        'form': form,
        'categories': categories
    }
    return render(request, 'login.html', context)

ecomapp/templates/account.html
{% extends 'base.html' %}


{% block content %}

<h3 class="text-center">Personal Area {{ request.user }}</h3>
<hr>
<h4 class="text-center">Your orders</h4>
<table class='table'>
    <tr style='background: lightcoral;'>
        <td class='text-center'>Order number</td>
        <td class='text-center'>Order date</td>
        <td class='text-center'>Order status</td>
        <td class='text-center'>Order cost</td>
        <td class='text-center'>Order details</td>
        <td></td>
    </tr>
    {% for item in order %}
    <tr>
        <td class='text-center' style='padding-top: 20px; padding-bottom: 20px;'>{{ item.id }}</td>
        <td class='text-center' style='padding-top: 20px; padding-bottom: 20px;'>{{ item.date }}</td>
        <td class='text-center' style='padding-top: 20px; padding-bottom: 20px;'>{{ item.status }}</td>
        <td class='text-center' style='padding-top: 20px; padding-bottom: 20px;'>{{ item.total }}</td>
        <td class='text-center' style='padding-top: 20px; padding-bottom: 20px;'><button type="button" class="btn btn-primary btn-md" data-toggle="modal" data-target="#myModal-{{ item.id }}">
         Order details
        </button></td> 
    </tr>
    {% endfor %}
</table>
  
  <!-- Модаль -->
  {% for item in order %} 
  <div class="modal fade" id="myModal-{{ item.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Order № {{ item.id }}</h4>
        </div>
        <div class="modal-body">
        <h3>Product</h3>
            <table class="table">
                {% for order_item in item.items.items.all %}
                    <tr>
                        <td>{{ order_item.product.title }}</td>
                        <td>{{ order_item.qty }}pcs.</td>
                        <td>{{ order_item.item_total }} UAH.</td>
                    </tr>
                {% endfor %}
                    <tr>
                        <td></td>
                        <td>Total:</td>
                        <td><strong>{{ item.items.cart_total }} UAH.</strong></td>
                    </tr>
            </table>
        <h3>Customer</h3>
        <p>Name: {{ item.first_name }}</p>
        <p>Last Name: {{ item.last_name }}</p>
        <p>Phone: {{ item.phone }}</p>
        <h3>Type of delivery</h3>
        <p>{% if item.buying_type == 'self' %} Without delivery {% else %} Delivery {% endif %}</p>
        <p>{% if item.buying_type == 'delivery' %} {{ item.address }}{% endif %}</p>
        <h3>Comments to the order</h3>
        <p>{{ item.comments }}</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
{% endfor %}
{% endblock content %}

ecomapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="shortcut icon" href='{% static "img/if_Apple.png" %}' type="image/x-icon"/>
    <title>Shop</title>

    <!-- Bootstrap Core CSS -->    
    <link href='{% static "css/bootstrap.min.css" %}' rel="stylesheet">

    <!-- Custom CSS -->
    <link href='{% static "css/shop-homepage.css" %}' rel="stylesheet">

 
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

 
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Apple Shop</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                {% if not request.get_full_path == '/' %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Category <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            {% for category in categories %}
                            <li><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endif %}   
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if not request.user.is_authenticated %}
                    <li>
                        <p class='navbar-text' style='color: khaki'>Hello Guest</p>
                    </li>
                    <li>
                        <a href='{% url "login" %}'>Login</a>
                    </li>
                    <li>
                        <a href='{% url "registration" %}'>Sign up</a>
                    </li>
                    {% else %}
                    <li>
                        <h4 class='navbar-text' style='color: lawngreen'>Hello, {{ request.user }}</h4>
                    </li>
                    <li>
                        <a href='{% url "account" %}'>Personal Area</a>
                    </li>
                    <li>
                        <a href='{% url "logout" %}'>Log out</a>
                    </li>
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href='{% url "cart" %}'><span  class="glyphicon glyphicon-shopping-cart
                        " class='badge' id='cart_count'>{% if not request.session.total %} 0 {% else %} {{ request.session.total }} {% endif %}</span></a></li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">
    {% block content %}
        <div class="row">

            <div class="col-md-3">
                <p class="lead">Shop Name</p>
                <div class="list-group">
                {% for category in categories %}
                    <a href="{{ category.get_absolute_url }}" class="list-group-item">{{ category.name }}</a>
                {% endfor%}
                </div>
            </div>

            <div class="col-md-9">

                <div class="row carousel-holder">

                    <div class="col-md-12">
                        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                {% for product in products %}
                                    {% if forloop.first %}
                                    <div class="item active">
                                        <img class="slide-image" src="{{ product.image.url }}" alt="" style='padding-left:30%; width:70%; height: 280px;'>
                                        <br>
                                        <p class='text-center'><a href='{{ product.get_absolute_url }}'><button class='btn btn-primary'>{{ product.title }}</button></a></p>
                                    </div>
                                    {% else %}
                                    <div class="item">
                                        <img class="slide-image" src="{{ product.image.url }}" alt="" style='padding-left:30%; width:70%; height: 280px;'>
                                        <br>
                                        <p class='text-center'><a href='{{ product.get_absolute_url }}'><button class='btn btn-primary'>{{ product.title }}</button></a></p>
                                    </div>
                                    {% endif %}
                                {% endfor %}
                            </div>
                            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev" style='background: transparent;'>
                                <span class="glyphicon glyphicon-chevron-left" style='color: black;'></span>
                            </a>
                            <p class='text-center'></p><a class="right carousel-control" href="#carousel-example-generic" data-slide="next" style='background: transparent;'>
                                <span class="glyphicon glyphicon-chevron-right" style='color: black;'></span>
                            </a>
                        </div>
                    </div>

                </div>

                <div class="row">
                    {% for product in products %}
                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail" style='height: 420px; position: relative;'>
                            <img src="{{ product.image.url }}" alt="" style='width:100%; height:250px;'>
                            <div class="caption">
                                <h4 class="pull-right">{{ product.price }} UAH.</h4>
                                <h5 class='text-center'><strong><a href="{{ product.get_absolute_url }}">{{ product.title }}</a></strong>
                                </h5>
                                <h3 class='text-center'>{{ product.price }} UAH.</h3>
                                <div style='position: absolute; bottom: 0; right:40px;'>
                                {% if request.user.is_authenticated %}
                                <p class='text-right'><a href='#' class='add_to_cart' data-slug='{{ product.slug }}'><button class='btn btn-danger'>add to</button></p>
                                {% endif %}
                                </div>
                            </div> 
                        </div>
                    </div>
                    {% endfor %}
                </div>

            </div>

        </div>

    </div>
    <!-- /.container -->
    
    <div class="container">

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </footer>

    </div>
    {% endblock content %}
    <!-- /.container -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    
    <script src='{% static "js/bootstrap.js" %}'></script>

    <!-- jQuery -->
    <script src='{% static "js/jquery.js" %}'></script>

<script>
$(document).ready(function(){
    $('.add_to_cart').on('click', function(e){
        e.preventDefault()
        product_slug = $(this).attr('data-slug')
        data = {
            product_slug: product_slug
        }
        $.ajax({
            type: "GET",
            url: '{% url "add_to_cart" %}',
            data: data,
            success: function(data){
                $("#cart_count").html(data.cart_total)
            }
        })
    })
})
</script>

</body>

</html>

ecomapp/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class='col-sm-12'>
    <h2>{{ category.name }}</h2>
    <hr>
    {% for product in products_of_category %}
    <div class='col-sm-4'>
        <img src='{{ product.image.url }}' style='width:100%; height: 300px;'>
        <a href='{{ product.get_absolute_url }}'><h4 class='text-center'>{{ product.title }}</h4></a>
        <p class='text-center' style='font-size:25px;'>Price: <strong>{{ product.price }} UAH.</strong></p>
        {% if request.user.is_authenticated %}<a href='#' class='add_to_cart' data-slug='{{ product.slug}}'><button class='btn btn-danger'>Add to</button></a>{% else %}
        <p class='text-center'>Only authorized users can order products. Please<a href='#'> login</a> or <a href=''>register</a>.</p>{% endif %}
    </div>
    {% endfor %}
</div>

<script src="{% static 'js/jquery.js' %}"></script>
<script>
$(document).ready(function(){
    $('.add_to_cart').on('click', function(e){
        e.preventDefault()
        product_slug = $(this).attr('data-slug')
        data = {
            product_slug: product_slug
        }
        $.ajax({
            type: "GET",
            url: '{% url "add_to_cart" %}',
            data: data,
            success: function(data){
                $("#cart_count").html(data.cart_total)
            }
        })
    })
})
</script>
{% endblock content %}

ecomapp/templates/checkout.html
{% extends 'base.html' %}

{% block content %}
<h3 class='text-center'>Your pre-order</h3>
<br>
<table class='table'>
    <tr>
        <td class='text-center'><strong>Product</strong></td>
        <td class='text-center'><strong>Quantity</strong></td>
        <td class='text-center'><strong>Price</strong></td>
        <td class='text-center'><strong></strong></td>
    </tr>
    {% for item in cart.items.all %}
    <tr class=>
        <td class='text-center'>{{ item.product.title }}</td>
        <td class='text-center'>{{ item.qty }}</td>
        <td class='text-center'>{{ item.item_total }} UAH.</td>
        <td></td>
    </tr>   
    {% endfor %}
    <tr>
        <td></td>
        <td class='text-center'><strong>Total: </strong></td>
        <td class='text-center'><strong>{{ cart.cart_total }} UAH.</strong></td>
        <td></td>
    </tr>
</table>
<a href='{% url "create_order" %}' class='pull-right'><button class='btn btn-success'>order placement</button></a>
{% endblock content %}

ecomapp/templates/order.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<form action='{% url "make_order" %}' method="POST">
{% csrf_token %}
    <div class='col-sm-4'>
        {{ form.name|as_crispy_field }}
    </div>
    <div class='col-sm-4'>
        {{ form.last_name|as_crispy_field }}
    </div>
    <div class='col-sm-4'>
        {{ form.phone|as_crispy_field }}
    </div>
    {{ form.buying_type|as_crispy_field }}
    {{ form.address|as_crispy_field }}
    {{ form.date|as_crispy_field }}
    {{ form.comments|as_crispy_field }}
    <input type='submit' class='btn btn-success' value='order placement'>
</form>
<script src='{% static "js/jquery.js" %}'></script>
<script>
    $(document).ready(function(){
        $('#div_id_address').css('display', 'none')
        $('#id_buying_type').on('click', function(){
            buying_type = $(this).val()
            if(buying_type == 'delivery'){
                $('#div_id_address').css('display', 'block')
            }else{
                $('#div_id_address').css('display', 'none')
            }
        })
        $('#id_date_month').css('width', '120px')
        $('#id_date_month').css('display', 'inline')
        $('#id_date_year').css('width', '80px')
        $('#id_date_year').css('display', 'inline')
        $('#id_date_day').css('width', '70px')
        $('#id_date_day').css('display', 'inline')
    })
</script>
{% endblock content %}

ecomapp/templates/thank_you.html
{% extends 'base.html' %}

{% block content %}
<div class='col-sm-8 col-sm-offset-2'>
    <h3 class='text-center'>Thank you for your order! It is accepted for processing. In the near future the manager will contact you.</h3>
    <p class='text-center'><a href='/'><button class='btn btn-default'>to shop</button></a></p>
</div>
{% endblock content %}